import { publicIps } from "../../../api/public-ips.ts";
import { command, flag, flags } from "../../../zcli.ts";
import { asserts } from "../../../lib/asserts.ts";
import { dataTable } from "../../../lib/data-table.ts";
import { loading } from "../../../lib/loading.ts";
import * as psFlags from "../../../flags.ts";
import { pickJson } from "../../../lib/pick-json.ts";
import { config } from "../../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const list = command("list", {
  short: "List public IPs.",
  long: ({ root }) => `
    List public IPs in your team or project.

    Pick a subset of fields to display:
    \`\`\`
    ${root.name} public-ip list -F name -F dtModified
    \`\`\`
  `,
  commands: subCommands,
  flags: psFlags.paginator.merge(flags({
    "region": flag({
      aliases: ["r"],
      short: "Filter by region.",
    }).ostring(),
  })),
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(
  async function* ({ flags }) {
    const team = await config.get("team");
    asserts(team, "You must be in a team to list public IPs.");
    const result = await loading(
      publicIps.list({
        limit: flags.limit,
        after: flags.after,
        orderBy: "dtCreated",
        order: flags.asc ? "asc" : undefined,
        region: flags.region,
      }),
      { enabled: !flags.json },
    );

    asserts(result.ok, result);

    if (!flags.json) {
      for await (const line of dataTable(result.data.items, flags.fields)) {
        yield line;
      }
    } else {
      yield pickJson(result.data, flags.fields);
    }
  },
);
