import { args, command, z } from "../../zcli.ts";
import { open } from "../../deps.ts";
import { env } from "../../env.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const docs = command("docs", {
  short: "Open Paperspace documention in your default browser.",
  long: `
    This command opens the Paperspace documentation in your browser.
    You can optionally pass an argument that will take you to a specific 
    docs page.

    Valid pages are:
      - \`d\`, \`deployment\`
  `,
  commands: subCommands,
  args: args()
    .tuple([z.enum(["d", "deployment"]).describe("The page to open")])
    .optional(),
}).run(function* ({ args }) {
  yield "Opening Paperspace documentation...";
  const url = new URL(env.get("PAPERSPACE_DOCS_URL"));

  if (args[0]) {
    url.pathname = {
      d: "/gradient/deployments/",
      deployment: "/gradient/deployments/",
    }[args[0]] ?? "/";
  }

  open(url + "");
});
