# DO NOT EDIT
# -----------
# This file is generated by the `Paperspace/cli` repository and automatically 
# merged into the `Paperspace/homebrew-tap` repository. Any changes made to this
# file will be overwritten.

# typed: false
# frozen_string_literal: true

class Pscale < Formula
  desc "The Paperspace CLI"
  homepage "https://github.com/Paperspace/cli"
  version "{{PSPACE_VERSION}}"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Paperspace/cli/releases/download/v{{PSPACE_VERSION}}/pspace-macos-arm.zip"
      sha256 "{{PSPACE_SHA256_MACOS_ARM}}"

      def install
        bin.install "pspace"
        generate_completions_from_executable(bin/"pspace", "completions", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Paperspace/cli/releases/download/v{{PSPACE_VERSION}}/pspace-macos.zip"
      sha256 "{{PSPACE_SHA256_MACOS}}"

      def install
        bin.install "pspace"
        generate_completions_from_executable(bin/"pspace", "completions", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Paperspace/cli/releases/download/v{{PSPACE_VERSION}}/pspace-linux.zip"
      sha256 "{{PSPACE_SHA256_LINUX}}"

      def install
        bin.install "pspace"
        generate_completions_from_executable(bin/"pspace", "completions", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/pspace --version"
  end
end