import { secretSchema } from "./../schemas.ts";
import { projectSecrets } from "../../../api/projects.ts";
import { teamSecrets } from "../../../api/teams.ts";
import { config } from "../../../config.ts";
import { asserts } from "../../../lib/asserts.ts";
import { findProject } from "../../../lib/find-project.ts";
import { loading } from "../../../lib/loading.ts";
import { input } from "../../../prompts/input.ts";
import { confirm } from "../../../prompts/confirm.ts";
import { args, command } from "../../../zcli.ts";
import { secretFlags } from "../flags.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const delete_ = command("delete", {
  short: "Delete a secret",
  long: `
    Delete a secret from a project or team.
  `,
  commands: subCommands,
  args: args().tuple([
    secretSchema.shape.name.describe("The name of the secret to delete"),
  ]).optional(),
  flags: secretFlags,
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(
  async function* ({ args, flags }) {
    let [name] = args;

    if (!name) {
      name = await input("Name:", {
        filter: (v) => !!v.sequence.match(/[a-zA-Z0-9_]/),
      });
      asserts(name, "A secret name is required");
    }

    const parsedName = secretSchema.shape.name.safeParse(name);
    asserts(
      parsedName.success,
      "error" in parsedName ? parsedName.error : "",
    );

    if (!flags.global) {
      const project = await findProject({
        id: flags["project-id"],
        cwd: flags.cwd,
        quiet: flags.json,
      });

      const response = await loading(
        projectSecrets.delete({ id: project.id, name }),
      );

      asserts(response.ok, response);
      const result = response.data;

      if (flags.json) {
        yield JSON.stringify(result, null, 2);
      } else {
        yield `Deleted secret "${name}" in project "${project.name}"`;
      }
    } else {
      const team = await config.get("team");
      asserts(team, "A team is required");

      if (!flags.json) {
        asserts(
          await confirm(
            `Are you sure you want to delete your global secret "${name}" in team "${team}"?`,
          ),
          "Aborted",
        );
      }

      const response = await loading(
        teamSecrets.delete({ id: team, name }),
      );

      asserts(response.ok, response);
      const result = response.data;

      if (flags.json) {
        yield JSON.stringify(result, null, 2);
      } else {
        yield `Deleted secret "${name}" in team "${team}"`;
      }
    }
  },
);
