import { command } from "../../../zcli.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this 
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const delete_ = command("delete", {
  short: "",
  commands: subCommands,
}).run(
  ({ args, flags, ctx }) => {
    console.log('Arguments:', args);
    console.log('Flags:', flags);
    console.log('Context:', ctx);
  },
);
