import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { del } from "./delete/mod.ts";
import { env } from "../../env.ts";
import { start } from "./start/mod.ts";
import { stop } from "./stop/mod.ts";
import { restart } from "./restart/mod.ts";
import { update } from "./update/mod.ts";

export const defaultFields = [
  "id",
  "name",
  "state",
  "region",
  "machineType",
  "privateIp",
  "publicIp",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  get,
  list,
  start,
  stop,
  restart,
  del,
  update,
];

export const machine = command("machine", {
  short: "Manage your Paperspace machines",
  long: `
    Manage your Paperspace machines.

    For more information, see  ${new URL(
    "/machines",
    env.get("PAPERSPACE_DOCS_URL"),
  )}.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of machine.help(ctx)) {
    yield line;
  }
});
