import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { env } from "../../env.ts";
import { del } from "./delete/mod.ts";

export const defaultFields = [
  "id",
  "name",
  "operatingSystemLabel",
  "defaultSizeGb",
  "parentMachineId",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  get,
  list,
  del,
];

export const customTemplate = command("custom-template", {
  short: "Manage your custom templates",
  long: `
    Manage your custom templates. Custom templates are a backup of your
    machine's disk. They can be used to create additional machines. You
    can use them to prepopulate a machine with your desired software stack.

    For more information, see ${new URL(
    "/compute/custom-templates",
    env.get("PAPERSPACE_DOCS_URL"),
  )}.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of customTemplate.help(ctx)) {
    yield line;
  }
});
