import { command } from "../../zcli.ts";
import { set } from "./set/mod.ts";
import { get } from "./get/mod.ts";
import { delete_ } from "./delete/mod.ts";
import { config as psConfig, configPaths } from "../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [set, get, delete_];

export const config = command("config", {
  short: "Manage your local Paperspace configuration.",
  long: `
    This command manages your Paperspace configuration. You can use it to set, get, and 
    delete configuration values. Running this command without any subcommands will print 
    your current configuration.

    Your configuration is stored in a TOML file at \`~/.paperspace/config.toml\`. 

    For example, to set the current team, run: 
    \`\`\`
    pspace config set team "my-team"
    \`\`\`
  `,
  commands: subCommands,
}).run(async function* () {
  for (const key of configPaths) {
    // @ts-expect-error: it's fine
    const value = await psConfig.get(key);
    if (value === undefined) continue;
    yield `${key} = ${JSON.stringify(value)}`;
  }
});
