import { command } from "../../../zcli.ts";
import { create } from "./create/mod.ts";
import { list } from "./list/mod.ts";
import { delete_ } from "./delete/mod.ts";

export const defaultFields = [
  "id",
  "name",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  list,
  create,
  delete_,
];

export const tag = command("tag", {
  short: "Manage your Paperspace project tags.",
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of tag.help(ctx)) {
    yield line;
  }
});
