import { path } from "../../deps.ts";
import { args, command, z } from "../../zcli.ts";
import { degit } from "../../lib/degit.ts";
import * as psFlags from "../../flags.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const init = command("init", {
  short: "Create a new Paperspace app",
  long: `
    Create a new Paperspace app. This will create a new directory with a
    default app structure. You can optionally specify a name for the app
    and a template to use. If no template is specified, the default
    template will be used.

    Create a new app in the current directory.
    \`\`\`
    pspace init
    \`\`\`

    Create a new app named "my-app" relative to the current directory.
    \`\`\`
    pspace init my-app
    \`\`\`

    Create a new app named "my-app" relative to the current directory using
    a template from the Paperspace GitHub organization.
    \`\`\`
    pspace init my-app -t Paperspace/gradio-demo
    \`\`\`
  `,
  commands: subCommands,
  args: args({
    short:
      "The name of the app to create. Defaults to the current directory name.",
  }).tuple([z.string()]).optional(),
  flags: psFlags.degit,
}).run(
  async ({ args, flags }) => {
    const dest = path.join(Deno.cwd(), args[0] ?? ".tmp");
    const { template, mode } = flags;

    if (template) {
      await degit({ mode, src: template, dest });
    }
  },
);
