import { command, flags } from "../../../../zcli.ts";
import { args, z } from "../../../../zcli.ts";
import { input } from "../../../../prompts/input.ts";
import { asserts } from "../../../../lib/asserts.ts";
import { loading } from "../../../../lib/loading.ts";
import { dataTable } from "../../../../lib/data-table.ts";
import { pickJson } from "../../../../lib/pick-json.ts";
import * as psFlags from "../../../../flags.ts";
import { defaultFields } from "../mod.ts";
import { projects, projectTags } from "../../../../api/projects.ts";
import { select } from "../../../../prompts/select.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const create = command("create", {
  short: "Create a new project tag",
  long: `
    Create a new project tag. This command will prompt you for a name if you don't
    provide one.
  `,
  commands: subCommands,

  args: args({ short: "Create a project tag with these properties." }).tuple([
    z.string().describe("The project ID to create a tag for."),
    z.string().describe("The name of the project tag to create."),
  ]).optional(),

  flags: flags({
    fields: psFlags.fields,
  }),

  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(async function* ({ args, flags }) {
  let [projectId, name] = args;

  if (!projectId) {
    const existingProjects = await loading(projects.list({ limit: 50 }));
    asserts(existingProjects.ok, existingProjects);

    const selected = await select(
      "Select a project:",
      existingProjects.data.items,
      {
        filter(input, option) {
          return option.name.toLowerCase().startsWith(input);
        },
        renderOption(option, isSelected) {
          return `${isSelected ? ">" : " "} ${option.name}`;
        },
      },
    );

    asserts(selected, "No project selected.");
    projectId = selected.id;
  }

  if (!name) {
    name = await input("Tag name:");
    asserts(name, "You must provide a name for the project tag.");
  }

  const result = await loading(projectTags.create({ id: projectId, name }), {
    enabled: !flags.json,
  });
  asserts(result.ok, result);

  if (!flags.json) {
    for await (
      const line of dataTable([result.data], flags.fields ?? defaultFields)
    ) {
      yield line;
    }
  } else {
    yield pickJson(result.data, flags.fields);
  }
});
