import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { list } from "./list/mod.ts";
import { del } from "./delete/mod.ts";
import { restore } from "./restore/mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  list,
  restore,
  del,
];

export const snapshot = command("snapshot", {
  short: "Manage your snapshots",
  long: `
    Manage your snapshots. Snapshots are copies of your machine's disk at a point in time.
    They can be used to restore the machine to its previous state. Using snapshots is recommended
    before taking any action that could affect the usability of the machine or its network connection.

    For more information, see https://docs.paperspace.com/storage/snapshots.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of snapshot.help(ctx)) {
    yield line;
  }
});
