import { storageProviders } from "../../../../api/storage-providers.ts";
import { fields } from "../../../../flags.ts";
import { asserts } from "../../../../lib/asserts.ts";
import { dataTable } from "../../../../lib/data-table.ts";
import { loading } from "../../../../lib/loading.ts";
import { pickJson } from "../../../../lib/pick-json.ts";
import { command, flag, flags } from "../../../../zcli.ts";
import { defaultFields } from "../../mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const s3 = command("s3", {
  short: "Create an S3 storage provider",
  long: `
    Create an S3 storage provider.
  `,
  commands: subCommands,
  flags: flags({
    fields,
  }).merge(flags({
    "name": flag({
      aliases: ["n"],
      short: "The name of the storage provider",
    }).string(),
    "is-team-default": flag({
      short: "Whether the storage provider is the team's default provider",
    }).oboolean(),
    "endpoint": flag({
      short: "The endpoint of the storage provider",
    }).ostring(),
    "bucket": flag({
      short: "The bucket of the storage provider",
    }).string(),
    "region": flag({
      short: "The region of the storage provider",
    }).ostring(),
    "access-key": flag({
      short: "The access key of the storage provider",
    }).string(),
    "secret-access-key": flag({
      short: "The secret access key of the storage provider",
    }).string(),
    "signature-version": flag({
      short: "The signature version of the storage provider",
    }).ostring(),
    "retain-data": flag({
      short: "Whether to retain data in the storage provider",
    }).oboolean(),
  })),
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
    requireInGoodStanding: true,
  },
}).run(
  async function* ({ flags }) {
    const response = await loading(
      storageProviders.create({
        name: flags.name,
        isTeamDefault: flags["is-team-default"],
        storageProviderType: "s3",
        s3Config: {
          endpoint: flags.endpoint,
          bucket: flags.bucket,
          region: flags.region,
          accessKey: flags["access-key"],
          secretAccessKey: flags["secret-access-key"],
          signatureVersion: flags["signature-version"],
          retainData: flags["retain-data"],
        },
      }),
    );

    asserts(response.ok, response);
    const result = response.data;

    if (flags.json) {
      yield pickJson(result, flags.fields);
    } else {
      for await (
        const line of dataTable([result], flags.fields ?? defaultFields)
      ) {
        yield line;
      }
    }
  },
);
