import { args, command } from "../../../../zcli.ts";
import { asserts } from "../../../../lib/asserts.ts";
import { dataTable } from "../../../../lib/data-table.ts";
import { loading } from "../../../../lib/loading.ts";
import * as psFlags from "../../../../flags.ts";
import { pickJson } from "../../../../lib/pick-json.ts";
import { defaultFields } from "../mod.ts";
import { projects } from "../../../../api/projects.ts";
import { projectTags } from "../../../../api/projects.ts";
import { select } from "../../../../prompts/select.ts";
import { z } from "../../../../zcli.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const list = command("list", {
  short: "List project tags.",
  long: ({ root }) => `
    List project tags in your team.

    Pick a subset of fields to display:
    \`\`\`
    ${root.name} project tags list -F id -F name -F dtCreated
    \`\`\`
  `,
  commands: subCommands,
  args: args().tuple([
    z.string().describe("The project ID to list tags for."),
  ])
    .optional(),
  flags: psFlags.paginator,
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(async function* ({ args, flags }) {
  let [projectId] = args;

  if (!projectId) {
    const existingProjects = await loading(projects.list({ limit: 50 }));
    asserts(existingProjects.ok, existingProjects);

    const selected = await select(
      "Select a project:",
      existingProjects.data.items,
      {
        filter(input, option) {
          return option.name.toLowerCase().startsWith(input);
        },
        renderOption(option, isSelected) {
          return `${isSelected ? ">" : " "} ${option.name}`;
        },
      },
    );

    asserts(selected, "No project selected.");
    projectId = selected.id;
  }

  const result = await loading(
    projectTags.list({
      id: projectId,
      ...flags,
      order: flags.asc ? "asc" : undefined,
    }),
    { enabled: !flags.json },
  );

  asserts(result.ok, result);

  if (!flags.json) {
    for await (
      const line of dataTable(result.data.items, flags.fields ?? defaultFields)
    ) {
      yield line;
    }
  } else {
    yield pickJson(result.data, flags.fields);
  }
});
