import { command } from "../../zcli.ts";
import { list } from "./list/mod.ts";
import { env } from "../../env.ts";

export const defaultFields = [
  "id",
  "name",
  "operatingSystemLabel",
  "defaultSizeGb",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  list,
];

export const osTemplate = command("os-template", {
  short: "List OS templates",
  long: `
    List OS templates. OS templates are pre-configured virtual machines that
    you can use to create a new machine.

    For more information, see ${new URL(
    "/compute/os-templates",
    env.get("PAPERSPACE_DOCS_URL"),
  )}.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of osTemplate.help(ctx)) {
    yield line;
  }
});
