import { projects } from "../../../api/projects.ts";
import { invariant } from "../../../lib/invariant.ts";
import { args, command, flag, flags, z } from "../../../zcli.ts";
import { select } from "../../../prompts/select.ts";
import { pick } from "../../../lib/pick.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const get = command("get", {
  short: "Get a project.",
  long: `
    Get a project by its ID. If you don't provide an ID, this command will
    prompt you for one based on the projects you have access to.
  `,
  commands: subCommands,
  args: args().tuple([z.string().describe("The project ID to get.")])
    .optional(),
  flags: flags({
    fields: flag({
      short: "The fields to include in the response.",
      aliases: ["F"],
    }).array(z.string()).optional(),
  }),
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(async ({ args, flags }) => {
  let [handle] = args;

  if (!handle) {
    const existingProjects = await projects.list({ limit: 50 });
    invariant(existingProjects.ok, existingProjects);

    const selected = await select(
      "Select a project:",
      existingProjects.data.items,
      {
        renderOption(option, isSelected) {
          return `${isSelected ? ">" : " "} ${option.name}`;
        },
      },
    );

    invariant(selected, "No project selected.");
    handle = selected.handle;
  }

  const result = await projects.get({ handle });
  invariant(result.ok, result);

  console.log(
    flags.fields ? pick(result.data, flags.fields) : result.data,
  );
});
