import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { del } from "./delete/mod.ts";
import { update } from "./update/mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  get,
  list,
  update,
  del,
];

export const autoscalingGroup = command("autoscaling-group", {
  short: "Manage your autoscaling groups",
  long: `
    Manage your autoscaling groups. Autoscaling groups enable using
    the Kubernetes cluster-autoscaler to automatically scale your cluster.
    You can also autoscaling groups as a primitive for your own autoscaler.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of autoscalingGroup.help(ctx)) {
    yield line;
  }
});
