/**
 * Do not edit this file manually. It is automatically generated by the build
 * process prior to distribution.
 */
export const __VERSION__ = "0.0.1-dev";
export const __COMMIT__ = "development";
