import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { delete_ } from "./delete/mod.ts";
import { update } from "./update/mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  get,
  list,
  delete_,
  update,
];

export const secret = command("secret", {
  short: "",
  commands: subCommands,
}).run(
  ({ args, flags, ctx }) => {
    console.log("Arguments:", args);
    console.log("Flags:", flags);
    console.log("Context:", ctx);
  },
);
