// deno-lint-ignore-file no-explicit-any
import { args, command, z } from "../../../zcli.ts";
import { config, configPaths } from "../../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const get = command("get", {
  short: "Get a configuration value.",
  long: `
    This command gets a configuration value. You can pass a key to get a specific
    value, or you can pass no arguments to get all configuration values.

    For example, to get the current team run:
    \`\`\`
    pspace config get team
    \`\`\`
  `,
  commands: subCommands,
  args: args({
    short: "The key to get.",
  }).tuple([z.enum(configPaths).describe("The configuration key.")]),
}).run(async function* ({ args }) {
  const [key] = args;
  const value = await config.get(key as any);
  yield value;
});
