import { open } from "../../lib/open.ts";
import { env } from "../../env.ts";
import { command } from "../../zcli.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const console = command("console", {
  short: "Open the Paperspace web console.",
  long: `
    This command opens the Paperspace web console in your browser.
  `,
  commands: subCommands,
}).run(function* () {
  yield "Opening the Paperspace console...";
  open(env.get("PAPERSPACE_CONSOLE_URL"));
});
