import { projects } from "../../../api/projects.ts";
import { dataTable } from "../../../lib/data-table.ts";
import { asserts } from "../../../lib/asserts.ts";
import { input } from "../../../prompts/input.ts";
import { args, command, flag, flags, z } from "../../../zcli.ts";
import * as psFlags from "../../../flags.ts";
import { pickJson } from "../../../lib/pick-json.ts";
import { loading } from "../../../lib/loading.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const update = command("update", {
  short: "Update an existing project.",
  long: `
    Update an existing project.

    Example:
    \`\`\`
    pspace project update psukfyemho7 --name my-cool-project
    \`\`\`
  `,
  use: `pspace project update <project-id> [flags]`,
  commands: subCommands,
  args: args().tuple([z.string().describe("The project ID to update.")]),
  flags: flags({
    name: flag({
      short: "The new name for the project.",
    }).string().min(1).max(120).optional(),
    fields: psFlags.fields,
  }),
}).run(
  async function* ({ args, flags }) {
    const [handle] = args;
    let { name } = flags;

    if (!name) {
      name = await input("New name:");
      asserts(name, "You must provide a new name for the project.");
    }

    const result = await loading(projects.update({ name, handle }), {
      enabled: !flags.json,
    });

    asserts(result.ok, result);

    if (!flags.json) {
      for await (const line of dataTable([result.data], flags.fields)) {
        yield line;
      }
    } else {
      yield pickJson(result.data, flags.fields);
    }
  },
);
