import { command } from "../../zcli.ts";
import { list } from "./list/mod.ts";

export const defaultFields = [
  "id",
  "teamId",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  list,
];

export const user = command("user", {
  short: "Information about users",
  long: `
    Show information about users.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of user.help(ctx)) {
    yield line;
  }
});
