import { asserts } from "../../../lib/asserts.ts";
import { loading } from "../../../lib/loading.ts";
import { args, command, flag, flags, z } from "../../../zcli.ts";
import { dataTable } from "../../../lib/data-table.ts";
import { fields } from "../../../flags.ts";
import { pickJson } from "../../../lib/pick-json.ts";
import { startupScripts } from "../../../api/startup-scripts.ts";
import { input } from "../../../prompts/input.ts";
import { defaultFields } from "../mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const update = command("update", {
  short: "Update a startup script",
  long: `
    Update a startup script.
  `,
  commands: subCommands,
  args: args().tuple([
    z.string().describe("The ID of the startup script to update"),
  ]).optional(),
  flags: flags({
    fields,
  }).merge(flags({
    "name": flag({
      aliases: ["n"],
      short: "The name of the startup script",
    }).ostring(),
    "script": flag({
      short: "The script to run",
    }).ostring(),
    "run-once": flag({
      short: "Whether to run once or on every boot",
    }).oboolean(),
    "enabled": flag({
      short: "Whether the startup script is enabled or not",
    }).oboolean(),
  })),
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(
  async function* ({ args, flags }) {
    let [id] = args;

    if (!id) {
      id = await input("ID:", {
        filter: (v) => !!v.sequence.match(/[a-zA-Z0-9_-]/),
      });
      asserts(id, "A startup script ID is required");
    }

    const response = await loading(
      startupScripts.update({
        id,
        name: flags.name,
        script: flags.script,
        isRunOnce: flags["run-once"],
        isEnabled: flags["enabled"],
      }),
    );

    asserts(response.ok, response);
    const result = response.data;

    if (flags.json) {
      yield pickJson(result, flags.fields);
    } else {
      for await (
        const line of dataTable([result], flags.fields ?? defaultFields)
      ) {
        yield line;
      }
    }
  },
);
