import { command } from "../../zcli.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { delete_ } from "./delete/mod.ts";
import { create } from "./create/mod.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [get, list, delete_, create];

export const deployment = command("deployment", {
  short: "Effortlessly deploy ML apps to Paperspace.",
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of deployment.help(ctx)) {
    yield line;
  }
});
