import { env } from "../../env.ts";
import { command } from "../../zcli.ts";
import { create } from "./create/mod.ts";
import { del } from "./delete/mod.ts";
import { get } from "./get/mod.ts";
import { list } from "./list/mod.ts";
import { update } from "./update/mod.ts";

export const defaultFields = [
  "id",
  "name",
];

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  create,
  get,
  list,
  del,
  update,
];

export const storageProvider = command("storage-provider", {
  short: "Manage your storage providers",
  long: `
    Manage your storage providers.

    For more information, see ${new URL(
    "/storage/storageProviders",
    env.get("PAPERSPACE_DOCS_URL"),
  )}.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of storageProvider.help(ctx)) {
    yield line;
  }
});
