import { command } from "../../zcli.ts";
import { assign } from "./assign/mod.ts";
import { claim } from "./claim/mod.ts";
import { list } from "./list/mod.ts";
import { release } from "./release/mod.ts";
import { env } from "../../env.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [
  assign,
  claim,
  list,
  release,
];

export const publicIp = command("public-ip", {
  short: "Manage your public IPs",
  long: `
    Manage your public IPs. Public IP addresses allow your compute machines to be reachable over the internet.

    For more information, see ${new URL(
    "/networking/public-ips",
    env.get("PAPERSPACE_DOCS_URL"),
  )}.
  `,
  commands: subCommands,
}).run(function* ({ ctx }) {
  for (const line of publicIp.help(ctx)) {
    yield line;
  }
});
