import { projectSecrets } from "../../../api/projects.ts";
import { command } from "../../../zcli.ts";
import { asserts } from "../../../lib/asserts.ts";
import { dataTable } from "../../../lib/data-table.ts";
import { loading } from "../../../lib/loading.ts";
import * as psFlags from "../../../flags.ts";
import { pickJson } from "../../../lib/pick-json.ts";
import { findProject } from "../../../lib/find-project.ts";
import { secretFlags } from "../flags.ts";
import { teamSecrets } from "../../../api/teams.ts";
import { config } from "../../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const list = command("list", {
  short: "List secrets.",
  long: ({ root }) => `
    List secrets in your team or project.

    Pick a subset of fields to display:
    \`\`\`
    ${root.name} secret list -F name -F dtModified
    \`\`\`
  `,
  commands: subCommands,
  flags: psFlags.paginator.merge(secretFlags),
  // We use command metadata in the `persistentPreRun` function to check if a
  // command requires an API key. If it does, we'll check to see if one is
  // set. If not, we'll throw an error.
  meta: {
    requireApiKey: true,
  },
}).run(
  async function* ({ flags }) {
    if (!flags.global) {
      const project = await findProject({
        id: flags["project-id"],
        cwd: flags.cwd,
        quiet: flags.json,
      });
      const result = await loading(
        projectSecrets.list({
          id: project.id,
          limit: flags.limit,
          after: flags.after,
          orderBy: flags.orderBy,
          order: flags.asc ? "asc" : undefined,
        }),
        { enabled: !flags.json },
      );

      asserts(result.ok, result);

      if (!flags.json) {
        for await (const line of dataTable(result.data.items, flags.fields)) {
          yield line;
        }
      } else {
        yield pickJson(result.data, flags.fields);
      }
    } else {
      const team = await config.get("team");
      asserts(team, "You must be in a team to list secrets.");
      const result = await loading(
        teamSecrets.list({
          id: team,
          limit: flags.limit,
          after: flags.after,
          orderBy: flags.orderBy,
          order: flags.asc ? "asc" : undefined,
        }),
        { enabled: !flags.json },
      );

      asserts(result.ok, result);

      if (!flags.json) {
        for await (const line of dataTable(result.data.items, flags.fields)) {
          yield line;
        }
      } else {
        yield pickJson(result.data, flags.fields);
      }
    }
  },
);
